Create bloc_presentation_test package
leancodepl/bloc_presentation pull request #18
Opened 2023-05-28 15:07 UTC by KrzysztofMamak

2023-05-28 16:52 UTC, shilangyu reviewed
- please remove `mocktail` from the main package deps
- we aren't moving the main package to `packages`?
- we will need a CI for this new package

2023-05-28 16:52 UTC, shilangyu commented on packages/bloc_presentation_test/pubspec.yaml
> +  flutter_bloc: ^8.0.0
Do we need flutter in the testing package? Depending on `bloc` itself isnt enough?

2023-05-28 16:52 UTC, shilangyu commented on packages/bloc_presentation_test/CHANGELOG.md
> +- Initial release. Includes MockPresentationBloc / MockPresentationCubit and whenListenPresentation.
```suggestion
- Initial release. Includes `MockPresentationBloc` / `MockPresentationCubit` and `whenListenPresentation`.
```

2023-05-28 16:52 UTC, shilangyu commented on example/test/widget_test_1.dart
we don't want to keep the examples?

2023-05-29 08:21 UTC, Albert221 commented
Please also move the `bloc_presentation` package to `packages` now

2023-05-30 19:50 UTC, KrzysztofMamak commented on example/test/widget_test_1.dart
Examples are restored

2023-06-03 21:23 UTC, bartekpacia commented on .github/workflows/bloc_presentation-publish.yml
> +          sdk: 2.18.6
Why not use `3.0.0`?

2023-06-03 21:24 UTC, bartekpacia commented on .github/workflows/bloc_presentation-test.yml
> +          restore-keys: ${{ runner.os }}-pub-
not needed, you already set `cache: true` in `Setup Flutter

2023-06-03 21:24 UTC, bartekpacia commented on .github/workflows/bloc_presentation-test.yml
> +      - name: Setup Flutter
Here "set up" is a verb, not a noun ("setup"), so:

```suggestion
      - name: Set up Flutter
```

2023-06-03 21:24 UTC, bartekpacia commented on .github/workflows/bloc_presentation-test.yml
> +        run: flutter --version
Not needed, it's in the logs of the previous step.

2023-06-03 21:28 UTC, bartekpacia commented on .github/workflows/bloc_presentation_test-publish.yml
> +        run: dart pub publish -f
Consider using our [`pub-release` GitHub Action](https://github.com/leancodepl/mobile-tools/blob/pub-release-v1/.github/actions/pub-release/action.yaml). It'll automatically create Releases on GitHub and link to changelogs.

[Example](https://github.com/leancodepl/patrol/releases) of how it looks like in Patrol. All these releases were generated by the `pub-release` action.

[Usage example](https://github.com/leancodepl/patrol/blob/b72d3026f87d763c7972ccfba85ed59b7dc26053/.github/workflows/patrol-publish.yaml#L37-L41).

2023-06-03 22:49 UTC, KrzysztofMamak commented on .github/workflows/bloc_presentation_test-publish.yml
> +        run: dart pub publish -f
Thanks for the example. Now it uses our custom GitHub Action.

2023-06-03 22:57 UTC, KrzysztofMamak commented on packages/bloc_presentation_test/pubspec.yaml
> +  flutter_bloc: ^8.0.0
`flutter_bloc` has been replaced with `bloc`.

2023-06-04 19:33 UTC, shilangyu reviewed
The example for `bloc_presentation_test` could be just a simple dart file with test examples, not a whole flutter project

2023-06-04 19:33 UTC, shilangyu commented on packages/bloc_presentation_test/pubspec.yaml
> +  flutter: '>=3.3.0'
I dont think we need flutter here at all

2023-06-05 14:59 UTC, Albert221 requested changes

2023-06-05 14:59 UTC, Albert221 commented on .github/workflows/bloc_presentation-publish.yml
> +          sdk: stable
Please use specific version, like 3.0.0. Using channels is prone to breaking errors in latest versions we do not yet plan to use/support

2023-06-05 14:59 UTC, Albert221 commented on .github/workflows/bloc_presentation-publish.yml
> +          channel: stable
Same here

2023-06-05 14:59 UTC, Albert221 commented on .github/workflows/bloc_presentation-test.yml
> +        run: dart pub publish --dry-run || true
Let's stick to using our GH action

2023-06-05 14:59 UTC, Albert221 commented on README.md
> +| [`bloc_presentation_test`][bloc_presentation_test-link] | [Documentation][bloc_presentation_test-documentation] | [![bloc_presentation_test pub.dev badge][bloc_presentation_test-pub-badge]][bloc_pr
```suggestion
| Package                                                 | Documentation                                         | pub                                                                                                                | CI                                                                                 |
|---------------------------------------------------------|:-----------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------:|
| [`bloc_presentation`][bloc_presentation-link]           | [Documentation][bloc_presentation-documentation]      | [![bloc_presentation pub.dev badge][bloc_presentation-pub-badge]][bloc_presentation-pub-badge-link]                | [![][bloc_presentation-build-badge]][bloc_presentation-build-badge-link]           |
| [`bloc_presentation_test`][bloc_presentation_test-link] | [Documentation][bloc_presentation_test-documentation] | [![bloc_presentation_test pub.dev badge][bloc_presentation_test-pub-badge]][bloc_presentation_test-pub-badge-link] | [![][bloc_presentation_test-build-badge]][bloc_presentation_test-build-badge-link] |
```

Formatted table

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation/README.md
> +Extends blocs with an additional stream which can serve as a way of indicating
```suggestion
Extends blocs with an additional stream serving as a way of indicating
```

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation/README.md
> +	listener: (context, event) {
Please use Flutter's formatting style: 2 spaces instead of a tab for indent

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation/README.md
> +[Here it is](../../example/lib).
```suggestion
[Here it is.](../../example/lib)
```

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation/example/pubspec.yaml
> +  bloc_presentation: 0.2.1+1
Use package from path instead

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation_test/LICENSE
> +   Copyright 2021 LeanCode Sp. z o.o.
2023

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation_test/README.md
> +flutter pub add bloc_presentation_test
```suggestion
flutter pub add --dev bloc_presentation_test
```

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation_test/README.md
> +After all, remember to close the StreamController. It can be achieved by calling `mockCubit`'s `close` method.
I'd mention that right after where you showed the `whenListenPresentation` returns a controller

2023-06-05 14:59 UTC, Albert221 commented on packages/bloc_presentation_test/example/pubspec.yaml
> +  bloc_presentation: 0.2.1+1
Use path

2023-06-05 20:17 UTC, bartekpacia commented on packages/bloc_presentation/README.md
> +[Here it is.](../../example/lib).
two dots?

2023-06-05 20:25 UTC, KrzysztofMamak commented on packages/bloc_presentation/README.md
> +[Here it is.](../../example/lib).
Updated to correct path.

2023-06-07 05:57 UTC, shilangyu approved these changes

2023-06-07 05:57 UTC, shilangyu commented on .github/workflows/bloc_presentation_test-publish.yml
> +          cache: true
flutter isnt needed for bloc_presentation_test

2023-06-07 05:57 UTC, shilangyu commented on .github/workflows/bloc_presentation_test-test.yml
> +          cache: true
Same here, we can matrix test dart versions instead

2023-06-07 15:32 UTC, Albert221 reviewed
Please move `.gitignore` from root to the `bloc_presentation`. This belonged here I see

2023-06-07 15:46 UTC, Albert221 commented on .github/workflows/bloc_presentation-publish.yml
>        - name: Set up Flutter
Actually we don't need to setup Flutter in _publish_ workflows. We only use `dart` in them

2023-06-07 15:46 UTC, Albert221 commented on packages/bloc_presentation/README.md
> +[Here it is.](example/lib).
Doubled dot

2023-06-07 15:46 UTC, Albert221 commented on packages/bloc_presentation/example/pubspec.yaml
> +    path: ../
Is slash needed?

2023-06-07 15:46 UTC, Albert221 commented on packages/bloc_presentation_test/README.md
> +A package which makes testing `bloc_presentation_mixin`ed `bloc`s / `cubit`s more straightforward.
Capitalization still not fixed here

2023-06-07 15:46 UTC, Albert221 commented on packages/bloc_presentation_test/README.md
> +First, create a mock class of your `BlocPresentationMixin`ed `Bloc` / `Cubit`.
```suggestion
First, create a mock class of your `BlocPresentationMixin`ed `Bloc`/`Cubit`.
```

2023-06-07 15:46 UTC, Albert221 commented on packages/bloc_presentation_test/README.md
> +re-mocked after calling `whenListenPresentation`) or directly by calling `controller`'s `close` method.
I think we can phrase it better, to make it easier to understand:

> The returned `StreamController` is disposed in cubit/bloc's `close()` method. If you override the stub for this method then you need to dispose the `controller` manually.

Keep it as a separate paragraph.

2023-06-07 15:46 UTC, Albert221 commented on packages/bloc_presentation_test/example/pubspec.yaml
> +    path: ../../bloc_presentation
I understand we cannot have it directly in `dependencies`?

2023-06-07 16:04 UTC, shilangyu commented on .github/workflows/bloc_presentation_test-publish.yml
> +          cache: true
Shit. That means my suggestions to remove flutter from `bloc_presentation_test`'s pubspec might be wrong too then. Not sure how pub handles such transitive flutter requirements.

2023-06-07 16:14 UTC, shilangyu commented on .github/workflows/bloc_presentation_test-publish.yml
> +          cache: true
Shit. That means my suggestions to remove flutter from `bloc_presentation_test`'s pubspec might be wrong too then. Not sure how pub handles such transitive flutter requirements.

2023-06-09 08:11 UTC, KrzysztofMamak commented on packages/bloc_presentation_test/example/pubspec.yaml
> +    path: ../../bloc_presentation
Yes. Publishable package cannot have path dependencies, so if we want to use bloc_presentation_test (which depends on bloc_presentation ^0.2.1+1), we need to override bloc_presentation dependency.

2023-06-09 08:20 UTC, Albert221 commented
But what for if we don't have anything to ignore in the root? Or do we?

2023-06-09 08:25 UTC, KrzysztofMamak commented
> But what for if we don't have anything to ignore in the root? Or do we?

We have .idea and .dart_tool directories.

2023-06-09 08:28 UTC, Albert221 commented
`.dart_tool` is a leftover after we had the package in the root.
`.idea` I believe is created automatically when you open the directory in IntelliJ? We don't have it in `flutter_corelibrary` repo, so I'd just not track it

2023-06-09 08:44 UTC, KrzysztofMamak commented
> `.dart_tool` is a leftover after we had the package in the root.
> `.idea` I believe is created automatically when you open the directory in IntelliJ? We don't have it in `flutter_corelibrary` repo, so I'd just not track it

Right. I removed it.

2023-06-09 08:48 UTC, Albert221 approved these changes

2023-06-09 08:58 UTC, merged