Bump dependency on `flutter_hooks`
leancodepl/bloc_presentation pull request #22
Opened 2023-07-16 11:34 UTC by bartekpacia

Fixes conflict with the newest version of `flutter_hooks`:

```
[discover_rudy] flutter pub get
Resolving dependencies...
Because bloc_presentation 0.2.1+1 depends on flutter_hooks ^0.18.1 and no versions of bloc_presentation match >0.2.1+1 <0.3.0, bloc_presentation ^0.2.1+1 requires flutter_hooks ^0.18.1.
So, because discover_rudy depends on both bloc_presentation ^0.2.1+1 and flutter_hooks ^0.19.0, version solving failed.
exit code 1
````

2023-07-16 11:35 UTC, bartekpacia commented on packages/bloc_presentation_test/.gitignore
> +pubspec.lock
not sure about this, see https://twitter.com/bartekpacia/status/1680540579518640130

2023-07-17 07:11 UTC, shilangyu approved these changes

2023-07-17 07:11 UTC, shilangyu commented on packages/bloc_presentation/CHANGELOG.md
> +# Unreleased
Do you plan to add more to this release? If not you can go ahead and version it

2023-07-17 07:12 UTC, shilangyu requested changes
Tests are failling for 3.3

2023-08-07 07:32 UTC, shilangyu commented
Can you also add a changelog entry for the `_test` package too? Since you bumped mocktail there

2023-08-07 07:33 UTC, bartekpacia commented
Sure, will do.

Also it looks like we'll have to bump min Flutter to 3.10.

2023-08-07 07:56 UTC, shilangyu commented on packages/bloc_presentation_test/CHANGELOG.md
> +  `whenListenPresentation`.
\>:|

2023-08-07 07:56 UTC, shilangyu commented on packages/bloc_presentation_test/CHANGELOG.md
> +  - Bump dependency on `leancode_lint` to `^5.0.0`
Since its a dev dep i dont think we need to mention it

2023-08-07 07:56 UTC, shilangyu commented on packages/bloc_presentation/CHANGELOG.md
> +# Unreleased
@bartekpacia let me know, unless you explicitly want to do it in a separate PR

2023-08-07 07:56 UTC, shilangyu commented on packages/bloc_presentation/CHANGELOG.md
> +  - Bump dependency on `mocktail` to `^1.0.0`
Same here. Let me know what you think

2023-08-07 08:03 UTC, bartekpacia commented on packages/bloc_presentation_test/CHANGELOG.md
> +  `whenListenPresentation`.
that's his fault! -> https://marketplace.visualstudio.com/items?itemName=stkb.rewrap

2023-08-07 08:04 UTC, bartekpacia commented on packages/bloc_presentation_test/CHANGELOG.md
> +  - Bump dependency on `leancode_lint` to `^5.0.0`
Yeah I agree

2023-08-07 08:06 UTC, bartekpacia commented
I'd prefer to bump versions in a separate PR.

At first I was okay with bumping versions here but I more changes were needed than I had expected at first.

2023-08-07 08:08 UTC, bartekpacia commented on packages/bloc_presentation/CHANGELOG.md
> +  - Bump dependency on `mocktail` to `^1.0.0`
Removed

2023-08-07 08:11 UTC, shilangyu approved these changes

2023-08-07 08:11 UTC, shilangyu commented on packages/bloc_presentation_test/CHANGELOG.md
> +- Bump minimum Flutter version to `3.10.0` (#22)
mockito version bump can stay, it was a non-dev dep

2023-08-07 08:13 UTC, Albert221 commented on packages/bloc_presentation/example/pubspec.yaml
> +  leancode_lint: '>=5.0.0'
Please use `^5.0.0`

2023-08-07 08:16 UTC, bartekpacia commented on packages/bloc_presentation/example/pubspec.yaml
> +  leancode_lint: '>=5.0.0'
thanks for the catch

btw, this got me thinking, why are we using `>=` for `sdk` and `flutter` constraints, and `^` for `dependencies`/`dev_dependencies`?

2023-08-07 08:17 UTC, bartekpacia commented on packages/bloc_presentation_test/CHANGELOG.md
> +- Bump minimum Flutter version to `3.10.0` (#22)
huh right, thx

I'm just so used to it being a dev dependency

2023-08-07 08:24 UTC, Albert221 commented on packages/bloc_presentation/example/pubspec.yaml
> +  leancode_lint: '>=5.0.0'
I assume this is because Flutter is a very big framework and breaking changes won't always affect a project, and developer & CI/CD have much greater influence on Flutter/Dart version used in comparison to just locking versions of dependencies

2023-08-07 08:28 UTC, bartekpacia commented on packages/bloc_presentation/example/pubspec.yaml
> +  leancode_lint: '>=5.0.0'
yeah, makes sense!

btw that's a nice read -> https://dart.dev/tools/pub/versioning

2023-08-07 08:28 UTC, bartekpacia commented on packages/bloc_presentation_test/CHANGELOG.md
> +- Bump minimum Flutter version to `3.10.0` (#22)
brought back

2023-08-07 09:01 UTC, merged