Use pub.dev automated publishing
leancodepl/bloc_presentation pull request #5
Opened 2023-02-17 15:58 UTC by Albert221

2023-02-17 15:59 UTC, bartekpacia approved these changes

2023-02-17 16:06 UTC, shilangyu approved these changes

2023-02-17 16:20 UTC, bartekpacia approved these changes

2023-02-20 09:33 UTC, bartekpacia requested changes

2023-02-20 09:33 UTC, bartekpacia approved these changes

2023-02-20 09:35 UTC, Albert221 commented on .github/workflows/test.yml
> +          version: ['3.3.10', '3.7.3']
> No one's gonna update these versions when 3.7.4, 3.7.5 etc comes out - and that's okay, there's no sense in doing it.
I agree, but I don't see why shouldn't we use most recent patch for those versions

2023-02-20 09:36 UTC, bartekpacia commented on .github/workflows/test.yml
> +          version: ['3.3.10', '3.7.3']
Because they won't be "most recent" in a few weeks, and IMHO, it looks ugly.

2023-02-20 09:41 UTC, Albert221 commented on .github/workflows/test.yml
> +          version: ['3.3.10', '3.7.3']
> https://github.com/subosito/flutter-action/issues/199

It incorrectly interprets `3.3.1`, not `3.3.10`

2023-02-20 09:42 UTC, bartekpacia commented on .github/workflows/test.yml
> +          version: ['3.3.10', '3.7.3']
ugh, right, sorry

remembered it other way around

2023-02-20 10:17 UTC, merged